name: vee
description: null
# Flutter version on machine: 3.29.2
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.2+1
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path_drawing: ^1.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  shared_preferences: ^2.2.3
# uni_links: ^0.5.1
dev_dependencies:
  bloc_test: ^9.1.6 # Unit testing for Bloc

  # Code generation
  build_runner: ^2.4.8 # For generating *.g.dart files

  flutter_lints: ^3.0.1 # Recommended lints for Flutter apps
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2 # Generates Freezed classes (with build_runner)
  json_serializable: ^6.7.1 # Generates toJson/fromJson
  mockito: ^5.4.4 # Mocking in tests
  retrofit_generator: ^8.0.6 # Generates Retrofit API client code

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/
    - assets/svgs/auth/
    - assets/icons/
    - assets/lottie/
    - assets/lang/

  fonts:
    - family: InstrumentSans
      fonts:
        - asset: assets/fonts/InstrumentSans/InstrumentSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/InstrumentSans/InstrumentSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/InstrumentSans/InstrumentSans-Regular.ttf
          weight: 400

flutter_assets:
  assets_path:
    - assets/images/
    - assets/svgs/
    - assets/svgs/auth/
    - assets/icons/
  output_path: lib/core/constants/
  filename: app_assets.dart
