name: vee
description: 
# Flutter version on machine: 3.29.2
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter icons (iOS style)
  cupertino_icons: ^1.0.6

  # State management
  flutter_bloc: ^8.1.3          # Bloc pattern for state management
  equatable: ^2.0.5             # Simplifies value comparisons (used with bloc)
  dartz: ^0.10.1                # Functional programming helpers (Either, Option)

  # Dependency injection
  get_it: ^7.6.7                # Service locator for DI

  # HTTP client
  dio: ^5.4.2+1                 # Powerful HTTP client

  # JSON serialization
  json_annotation: ^4.9.0       # For defining JSON-serializable models

  # Image caching
  cached_network_image: ^3.3.1  # Efficient network image caching

  # Localization
  easy_localization: ^3.0.3     # Easy internationalization support
  intl: ^0.19.0                 # Date/number formatting, required for localization

  # Fonts & styling
  flutter_svg: ^2.0.10+1        # Render SVG images
  path_drawing: ^1.0.1          # For drawing complex paths (e.g. SVG)

  # Responsive design
  flutter_screenutil: ^5.9.0    # Helps with responsive UI

  # Shared preferences
  shared_preferences: ^2.2.3    # Store simple key-value pairs locally


  # App launcher icon
  flutter_launcher_icons: ^0.13.1  # For generating app launcher icons

  # Native splash screen
  flutter_native_splash: ^2.3.8    # Auto-generated native splash screen

  # Logging
  logger: ^2.5.0                # Elegant and flexible logging

  # Freezed (used with json_serializable)
  freezed_annotation: ^2.4.1    # Model immutability & union types

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1         # Recommended lints for Flutter apps

  # Code generation
  build_runner: ^2.4.8          # For generating *.g.dart files
  json_serializable: ^6.7.1     # Generates toJson/fromJson
  freezed: ^2.5.2               # Generates Freezed classes (with build_runner)

  # Testing
  bloc_test: ^9.1.6             # Unit testing for Bloc
  mockito: ^5.4.4               # Mocking in tests

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/
    - assets/svgs/auth/
    - assets/icons/
    - assets/lottie/
    - assets/lang/

  fonts:
    - family: InstrumentSans
      fonts:
        - asset: assets/fonts/InstrumentSans/InstrumentSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/InstrumentSans/InstrumentSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/InstrumentSans/InstrumentSans-Regular.ttf
          weight: 400

flutter_assets:
  assets_path:
    - assets/images/
    - assets/svgs/
    - assets/svgs/auth/
    - assets/icons/
  output_path: lib/core/constants/
  filename: app_assets.dart
