default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter build apk --release --flavor development --target lib/main_dev.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:596139652941:android:85aa9bdd78988ebb936904",
      firebase_cli_token: "1//03OSPCoaq_S8zCgYIARAAGAMSNwF-L9IryLiIN1bN9CwK3vUNsF3BXl8eOBQxE_Lm3peTuPoV3x8S4ytfFA0PpB3rjkgdvarl3ak",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-development-release.apk",
      android_artifact_type: "APK",
      testers: "ahmedredahmedd@gmail.com" 
    )   
  end
end
